config/routes.rb
HoursLogger::Application.routes.draw do
  
  resources :settings

  get '/' => 'time_cards#index'
  get '/time_cards/email' => 'time_cards#email'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  
  get "/signup", to: 'users#new', as: 'signup'
  resources :users

  get '/time_cards/:time', to: 'time_cards#stats', as: 'time_cards_by' # TODO this is so that you can do something like this: time_cards_by_path(:stats)
  
  resources :time_cards

  # get "/month" => 'time_cards#month'
  # get "/year" => 'time_cards#year'
  # get "/all" => 'time_cards#all'
  # get '/stats' => 'time_cards#stats'
  
  
 
  post '/stats' => 'time_cards#stats', as: 'stats'
  post '/' => 'time_cards#index'
  post '/cookies/new' => 'cookies#create'
  post '/login', to: 'sessions#create'
  post '/time_cards/email' => 'time_cards#email'
  post '/email' => 'time_careds#email_timer', as: 'email'
 

  get '/stats' => 'time_cards#stats'
  get '/email' => 'time_cards#email_timer'
 
  
  root to: 'time_cards#index'
  
  

end

app/views/notifier/timer_running.html.erb
<h4>Hi <%= @user.name %>,</h4>

<p>We just wanted to make sure you know timer is still running.</p>

<p>You started your timer:<br>
<%= @time_started.to_datetime.strftime("%l:%M%P") %> on <%= @time_started.to_datetime.strftime("%A, %h %e") %>
</p>

<p>
Our efforts are to HELP you ACCURATELY track your time, so we emailed you to make sure you are still working.  
If you need to fix your timer, you can do it here <%= link_to "Click Me", email_url( id: @user.id, time_started: @time_started), method: :post, class: "my_link" %>
</p>

<p>
You can change the settings on email notifications from your account settings. 
</p>

<p>
Many thanks from Hours Logger,
Drew, Matt, and George
</p>