config/routes.rb
HoursLogger::Application.routes.draw do
  
  resources :settings

  get '/' => 'time_cards#index'
  get '/time_cards/email' => 'time_cards#email'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  
  get "/signup", to: 'users#new', as: 'signup'
  resources :users

  get '/time_cards/:time', to: 'time_cards#stats', as: 'time_cards_by' # TODO this is so that you can do something like this: time_cards_by_path(:stats)
  
  resources :time_cards

  # get "/month" => 'time_cards#month'
  # get "/year" => 'time_cards#year'
  # get "/all" => 'time_cards#all'
  # get '/stats' => 'time_cards#stats'
  
  
 
  post '/stats' => 'time_cards#stats', as: 'stats'
  post '/' => 'time_cards#index'
  post '/cookies/new' => 'cookies#create'
  post '/login', to: 'sessions#create'
  post '/time_cards/email' => 'time_cards#email'
  post '/email' => 'time_careds#email_timer', as: 'email'
 

  get '/stats' => 'time_cards#stats'
  get '/email' => 'time_cards#email_timer'
 
  
  root to: 'time_cards#index'
  
  

end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:hours_before_email, :hours_alert, :days_before_reports, :generate_reports, :time_zone)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hours_before_email %><br>
    <%= f.number_field :hours_before_email %>
  </div>
  <div class="field">
    <%= f.label :hours_alert %><br>
    <%= f.check_box :hours_alert %>
  </div>
  <div class="field">
    <%= f.label :days_before_reports %><br>
    <%= f.number_field :days_before_reports %>
  </div>
  <div class="field">
    <%= f.label :generate_reports %><br>
    <%= f.check_box :generate_reports %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br>
    <%= f.text_field :time_zone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <thead>
    <tr>
      <th>Hours before email</th>
      <th>Hours alert</th>
      <th>Days before reports</th>
      <th>Generate reports</th>
      <th>Time zone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.hours_before_email %></td>
        <td><%= setting.hours_alert %></td>
        <td><%= setting.days_before_reports %></td>
        <td><%= setting.generate_reports %></td>
        <td><%= setting.time_zone %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hours before email:</strong>
  <%= @setting.hours_before_email %>
</p>

<p>
  <strong>Hours alert:</strong>
  <%= @setting.hours_alert %>
</p>

<p>
  <strong>Days before reports:</strong>
  <%= @setting.days_before_reports %>
</p>

<p>
  <strong>Generate reports:</strong>
  <%= @setting.generate_reports %>
</p>

<p>
  <strong>Time zone:</strong>
  <%= @setting.time_zone %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>