config/routes.rb
HoursLogger::Application.routes.draw do
  
  resources :settings

  get '/' => 'time_cards#index'
  get '/time_cards/email' => 'time_cards#email'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create]
  
  get "/signup", to: 'users#new', as: 'signup'
  resources :users

  get '/time_cards/:time', to: 'time_cards#stats', as: 'time_cards_by' # TODO this is so that you can do something like this: time_cards_by_path(:stats)
  
  resources :time_cards

  # get "/month" => 'time_cards#month'
  # get "/year" => 'time_cards#year'
  # get "/all" => 'time_cards#all'
  # get '/stats' => 'time_cards#stats'
  
  
 
  post '/stats' => 'time_cards#stats', as: 'stats'
  post '/' => 'time_cards#index'
  post '/cookies/new' => 'cookies#create'
  post '/login', to: 'sessions#create'
  post '/time_cards/email' => 'time_cards#email'
  post '/email' => 'time_careds#email_timer', as: 'email'
 

  get '/stats' => 'time_cards#stats'
  get '/email' => 'time_cards#email_timer'
 
  
  root to: 'time_cards#index'
  
  

end

app/models/time_card.rb
class TimeCard < ActiveRecord::Base
  belongs_to :user
  

end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController
  before_action :set_time_card, only: [:show, :edit, :update, :destroy]
  before_action :set_zone, only: [:month, :year, :all, :edit, :stats]
  
  RANDOM_QUOTES = ["Let's get to work.", "The best time to get it done is NOW!", "Hard work PAYS OFF!", "MORE GRINDING = MORE $$$", "Sleep is for people who are BROKE!", "Ridiculous, SICKENING Work Ethic ... #RSWE", "While you are sleeping, someone else is trying to beat you."]
  
  
  
  
  
  def index
	unless flash[:notice]
  		flash[:notice] = {:class => "login_notice", :body => RANDOM_QUOTES[Random.rand(7)] }
  	end
	
  	if notice
  		if flash[:notice][:body] == "To track your time, I need to know who you are."
  			flash[:notice] = {:class => "login_notice", :body => RANDOM_QUOTES[Random.rand(7)] }
  		end
  	end
  
	if !cookies[:user_id].present?
		flash[:notice] = {:class => "login_notice", :body => "To track your time, I need to know who you are."}
		redirect_to login_path
	end
  
	@time_card = TimeCard.new
  end
  
  
  
  def email_timer 
	@user = User.find_by_name(params[:id])
	if @user
		set_user_cookie(@user)
	end
	
    redirect_to root_url
  end
  
  
  
  
  def stats
	@total_hours = 0
	@date = Time.new
	@client = "New"
	@time = "stats"
	@month_selected_1 = 0
	@year_selected_1 = 0

	
	if !params[:time].present?
		flash[:notice] = nil
		
		beg_of_week = Time.now.at_end_of_week-8.day+1
		end_of_week = Time.now.at_end_of_week-1.day+1
		
		if params[:time_selected].present?
			beg_of_week = params[:time_selected]
			beg_of_week = beg_of_week.to_datetime
			end_of_week = params[:time_selected]
			end_of_week = (end_of_week.to_datetime+6.day+1)
			@time_selected = beg_of_week
		end

		beg_of_week = (beg_of_week-7.hours)
		end_of_week = (end_of_week-7.hours+48.hours)
		
		@time_cards = current_user.time_cards.where(time_started: beg_of_week .. end_of_week).order("date DESC")
	end
	
	
	if params[:time] == "stats"
		flash[:notice] = nil
		
		beg_of_week = Time.now.at_end_of_week-8.day+1
		end_of_week = Time.now.at_end_of_week-1.day+1
		
		if params[:time_selected].present?
			beg_of_week = params[:time_selected]
			beg_of_week = beg_of_week.to_datetime
			end_of_week = params[:time_selected]
			end_of_week = (end_of_week.to_datetime+6.day+1)
			@time_selected = beg_of_week
		end
		
		beg_of_week = (beg_of_week-7.hours)
		end_of_week = (end_of_week-7.hours+24.hours)
		
		@time_cards = current_user.time_cards.where(time_started: beg_of_week .. end_of_week).order("date DESC")
		
	end
	
	
	
	
	if params[:time] == "month"
	
		beg_of_month = Time.now.at_beginning_of_month
		end_of_month = Time.now.at_end_of_month
		
		if params[:time_selected].present?
			beg_of_month = params[:time_selected]
			beg_of_month = beg_of_month.to_datetime
			end_of_month = params[:time_selected]
			end_of_month = (end_of_month.to_datetime+1.month)
			@month_selected = beg_of_month
		end
	
		@time_cards = current_user.time_cards.where(date: beg_of_month .. end_of_month).order("date DESC")
	end
	
	
	
	

  if params[:time] == "year"
	
		beg_of_year = Time.now.at_beginning_of_year
		end_of_year = Time.now.at_end_of_year
		
		if params[:time_selected].present?
			beg_of_year = params[:time_selected]
			beg_of_year = beg_of_year.to_datetime
			end_of_year = params[:time_selected]
			end_of_year = (end_of_year.to_datetime+1.year)
			@year_selected = beg_of_year
		end
		
		@time_cards = current_user.time_cards.where(date: beg_of_year .. end_of_year).order("date DESC")
	end
		clients = @time_cards
		@clients = clients.uniq_by{|s| s.client}
		
	if params[:client].present?
		if params[:client] != "all"
			@time_cards = @time_cards.where(client: params[:client])
		end
	end
		
	
	
	# Total the Hours
	@time_cards.each do |time_card|
		@total_hours = (@total_hours+((time_card.time_stopped - time_card.time_started)/3600))
	end
	
  end
  
  
  
  
  
  
  
  def show
  end


  def new
    @time_card = TimeCard.new
  end

  
  def edit
  end

  def email
	@user = current_user
	@time_started = cookies[:start_time]
	Notifier.timer_running(@user, @time_started).deliver
	
	
    respond_to do |format|
      format.json { render json: "success"}
    end
  end
 
  
  
  def create
    # Store the current start and stop time in the users time card
	
	
    now = Time.now
    @time_card = TimeCard.new(time_card_params)
    @time_card.user_id = cookies[:user_id]
	
  	@time_card.time_stopped = now
  	@time_card.time_started= (now-params[:total_seconds].to_i)
  	@time_card.date = Time.now.in_time_zone("Pacific Time (US & Canada)").to_date

	if @time_card.client == ""
		@time_card.client = "No Client"
	end
	@time_card.client = @time_card.client.downcase
	
	if params[:end_time] == "true"
		utc_stop = Time.new(params[:time_card]["date(1i)"].to_i,
							params[:time_card]["date(2i)"].to_i,
							params[:time_card]["date(3i)"].to_i, 
							params[:time_card]["time_stopped(4i)"],
							params[:time_card]["time_stopped(5i)"],
							0, "-07:00")
							
		utc_stop = utc_stop.in_time_zone("UTC")
		@time_card.time_stopped = utc_stop
		
		utc_start = params[:start_time]
		utc_start = utc_start.to_datetime.in_time_zone("UTC")
		@time_card.time_started = utc_start
		
	end
	
    respond_to do |format|
      if @time_card.save
		flash[:notice] = {:class => "login_notice", :body => "Got it!  I logged your hours."}
        format.html { redirect_to root_url}
        format.json { render action: 'show', status: :created, location: @time_card }
      else
        format.html { render action: 'new' }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end


  
  
  
  def update
    respond_to do |format|
  		utc_start = Time.new(params[:time_card]["date(1i)"].to_i,
							params[:time_card]["date(2i)"].to_i,
							params[:time_card]["date(3i)"].to_i, 
							params[:time_card]["time_started(4i)"], 
							params[:time_card]["time_started(5i)"],
							0, "-07:00")
							   
  		utc_stop = Time.new(params[:time_card]["date(1i)"].to_i,
							params[:time_card]["date(2i)"].to_i,
							params[:time_card]["date(3i)"].to_i, 
							params[:time_card]["time_stopped(4i)"],
							params[:time_card]["time_stopped(5i)"],
							0, "-07:00")
		
		
  		utc_start = utc_start.in_time_zone("UTC")
  		utc_stop = utc_stop.in_time_zone("UTC")
  		date = Date.new(params[:time_card]["date(1i)"].to_i, params[:time_card]["date(2i)"].to_i, params[:time_card]["date(3i)"].to_i)
		
		
		client = params[:time_card]["client"].downcase

		if params[:time_card]["client"] == ""
		 client = "no client"
		end
		
		
  	  if @time_card.update(time_started: utc_start, time_stopped: utc_stop, message: params[:time_card]["message"], date: date, client: client )
  		  flash[:notice] = {:class => "login_notice", :body => "Successfully updated!"}
        format.html { redirect_to "/" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end
 

 
 
 
 
  def destroy
    @time_card.destroy
    respond_to do |format|
      format.html { redirect_to time_cards_by_path(:stats) }
      format.json { head :no_content } # TODO SUCCESS => TRUE {success: true}
    end
  end

  
  
  
  
  
  
private
  
  def set_zone
    Time.zone = "Pacific Time (US & Canada)"
  end
  

  def set_time_card
    @time_card = TimeCard.find(params[:id])
  end


  def time_card_params
    params.require(:time_card).permit(:time_started, :time_stopped, :client, :date, :message)
  end
  
end

app/helpers/time_cards_helper.rb
module TimeCardsHelper
end

app/views/time_cards/all.html.erb
	<div class="row">
		<a href="http://hourslogger.com/" id="link_back"><button class="col-xs-2"  id="back">Back</button></a>
		<div class="col-xs-10"></div>
	</div>
	
	<div class="header">
		<div class="row">
			<div class="col-xs-1 col-sm-2 col-lg-4"></div>
			<%= image_tag("logo.png", :id => "logo_3", :class => "col-xs-10 col-sm-8 col-lg-4") %>
			<div class="col-xs-1 col-sm-2 col-lg-4"></div>
		</div>
	</div>


	<div class="row">
		<div id="menu">
		<div class="col-xs-1 col-sm-2 col-lg-4"></div>
			<div class="col-xs-10 col-sm-8 col-lg-4">
			<p class="menu_item col-xs-3" ><%= link_to "Week", "/stats" %></p>
			<p class="menu_item col-xs-3" ><%= link_to "Month", "/month" %></p>
			<p class="menu_item col-xs-3" ><%= link_to "Year", "/year" %></p>
			<p class="menu_item col-xs-3" id="current">All</p>
		</div>
		<div class="col-xs-1 col-sm-2 col-lg-4"></div>
		</div>
	</div>
	

				
			
			
	<div class="row">	
		<div class="col-xs-1 col-sm-2 col-lg-4"></div>	
		<p class="col-xs-10 col-sm-8 col-lg-4" id="total">Total: <%=  number_with_precision(@hours_all, :precision => 2) %> hrs</p>
		<div class="col-xs-1 col-sm-2 col-lg-4"></div>
	</div>



	<% @time_cards.each do |time_card| %>
	<div class="container">
	
		<div class="<%= cycle("time_card" , "time_card_2" ) %>">
				
					<div class="row">
						<div class="col-xs-1"></div>
						<p class="col-xs-1" id="log"><%= @count = @count+1 %></p>
						<p class="col-xs-9" id = "date"><%= time_card.date.strftime("%A, %h %e %G") %></p>
						<div class="col-xs-1"></div>
					</div>
					
					<% 
						local_start	= Time.new
						local_stop	= Time.new
						local_start = time_card.time_started
						local_stop  = time_card.time_stopped
						
						
						local_start_1 = local_start
						local_stop_1 = local_stop
						local_start = local_start.strftime('%l:%M%P')
						local_stop = local_stop.strftime('%l:%M%P')
					%>
					
				<div class="row">
					<div class="col-xs-2"></div>
					<p class="col-xs-8" id="the_time"><%= local_start %> - <%= local_stop %></p>
					<%= link_to image_tag("edit.png", :class => "edit_icon"), edit_time_card_path(time_card) %>
				</div>
				
				<div class="row">
					<div class="col-xs-2"></div>
					<p class="col-xs-8" id="hours"><%= number_with_precision(((local_stop_1 - local_start_1)/3600), :precision => 2) %> hrs</p>
					
				</div>
				
				<div class="row">
				<div class="col-xs-2"></div>
				<p class="col-xs-7" id="message"><%= time_card.message %></p>
				<div class="col-xs-1"></div>
				<%= link_to image_tag("delete.png", :class => "cancel_icon"), time_card, method: :delete, data: { confirm: "Are you sure you want to delete this time card?" } %>
				</div>
		</div>
	</div>
	<% end %>


app/views/time_cards/edit.html.erb
<h1>Editing time_card</h1>

<%= render 'form' %>


<%= link_to 'Back', "/stats" %>

app/views/time_cards/email.html.erb
Hi

app/views/time_cards/home.html.erb
<p id="username"><%= current_user.name.present? ? current_user.name : "Guest" %></p>

<%= link_to logout_path do %>
	<p id="signout">Sign Out</p>
<%= end %>


<div class="container">
	<div class="row">
		<div class="col-xs-1 col-sm-3"></div>
		<%= image_tag("logo.png", :id => "logo_3", :class => "col-xs-10 col-sm-6") %>
		<div class="col-xs-1 col-sm-3"></div>
	</div>
	
	<% if notice %>
		<p id="notice" class="<%= flash[:notice][:class] %>"><%= flash[:notice][:body] %></p>
	<% end %>
	<br>
	<div class="col-xs-12 col-md-2"></div>
	<p  class="col-xs-12 col-md-8" id="time">Time Working: <span id="current_time">00:00:00</span></p>
	<div class="col-xs-12 col-md-2"></div>
	
	<%= render  "confirm" %>
	<div class="row">
		<div class="col-xs-2 col-sm-4"></div>
		<button class="button_3 col-xs-8 col-sm-4" id="working">Start Working</button>
		<button data-toggle="modal" data-target="#myModal" class="button_3 col-xs-8 col-sm-4" id="not_working">Stop Working</button>
		<div class="col-xs-2 col-sm-4"></div>
	</div>
	
	<div class="row">
		<div class="col-xs-2 col-sm-4"></div>
		<%= link_to "My Stats", time_cards_by_path(:stats), class: "button button_3 col-xs-8 col-sm-4", id: "stats" %>
		<div class="col-xs-2 col-sm-4"></div>
	</div>
</div>

<script>
	$( document ).ready(function() {
	if (($.cookie('start_time'))){
		start = new Date;
		start = Date.parse($.cookie('start_time'));
		$('#working').hide();
		$('#not_working').show();
		$('#notice').hide();
		x = window.setInterval(updateTime, 1000);
		intervalID = x;
	}
	});
</script>

app/views/time_cards/index.html.erb
<p id="username"><%= current_user.name %></p>

<%= link_to logout_path do %>
	<p id="signout">Sign Out</p>
<% end %>

<div id="div1"></div>


<div class="container">
	<div class="row">
		<div class="col-xs-1 col-sm-3"></div>
		<%= image_tag("logo.png", :id => "logo_3", :class => "col-xs-10 col-sm-6") %>
		<div class="col-xs-1 col-sm-3"></div>
	</div>
	
	<% if notice %>
		<p id="notice" class="<%= flash[:notice][:class] %>"><%= flash[:notice][:body] %></p>
	<% end %>
	<br>
	<div class="col-xs-12 col-md-2"></div>
	<p  class="col-xs-12 col-md-8" id="time">Time Working: <span id="current_time">00:00:00</span></p>
	<div class="col-xs-12 col-md-2"></div>
	
	<%= render  "confirm" %>
	
	<div class="row">
		<div class="col-xs-2 col-sm-4"></div>
		<button class="button_3 col-xs-8 col-sm-4" id="working">Start Working</button>
		<button data-toggle="modal" data-target="#myModal" class="button_3 col-xs-8 col-sm-4" id="not_working">Stop Working</button>
		<div class="col-xs-2 col-sm-4"></div>
	</div>
	
	<div class="row">
		<div class="col-xs-2 col-sm-4"></div>
		<%= link_to "My Stats", time_cards_by_path(:stats), class: "button_3 stats_button col-xs-8 col-sm-4", id: "stats" %>
		<div class="col-xs-2 col-sm-4"></div>
	</div>
</div>

<script>
	$( document ).ready(function() {
	if (($.cookie('start_time'))){
		start = new Date;
		start = Date.parse($.cookie('start_time'));
		$('#working').hide();
		$('#not_working').show();
		$('#notice').hide();
		x = window.setInterval(updateTime, 1000);
		intervalID = x;
	}
	});
</script>

app/views/time_cards/new.html.erb
<h1>New time_card</h1>

<%= render 'form' %>

<%= link_to 'Back', time_cards_path %>

app/views/time_cards/old_index.html.erb
<h1>Listing time_cards</h1>

<table>
  <thead>
    <tr>
      <th>Time started</th>
      <th>Time stopped</th>
      <th>Date</th>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @time_cards.each do |time_card| %>
      <tr>
        <td><%= time_card.time_started %></td>
        <td><%= time_card.time_stopped %></td>
        <td><%= time_card.date %></td>
        <td><%= time_card.message %></td>
        <td><%= link_to 'Show', time_card %></td>
        <td><%= link_to 'Edit', edit_time_card_path(time_card) %></td>
        <td><%= link_to 'Destroy', time_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time card', new_time_card_path %>

app/views/time_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time started:</strong>
  <%= @time_card.time_started %>
</p>

<p>
  <strong>Time stopped:</strong>
  <%= @time_card.time_stopped %>
</p>

<p>
  <strong>Date:</strong>
  <%= @time_card.date %>
</p>

<p>
  <strong>Message:</strong>
  <%= @time_card.message %>
</p>

<%= link_to 'Edit', edit_time_card_path(@time_card) %> |
<%= link_to 'Back', time_cards_path %>

app/views/time_cards/stats.html.erb
	<div class="row">
		<a href="/" id="link_back"><button class="col-xs-2"  id="back">Back</button></a>
		<div class="col-xs-10"></div>
	</div>
		
	<div class="header">
		<div class="row">
			<div class="col-xs-1 col-sm-2 col-lg-4"></div>
			<%= image_tag("logo.png", :id => "logo_3", :class => "col-xs-10 col-sm-8 col-lg-4") %>
			<div class="col-xs-1 col-sm-2 col-lg-4"></div>
		</div>
	</div>

	
	
	
	
	
	<!--  ***********************************************      Week Select     ***********************************************   -->
	
	
	
		<div class="row select_1">
			<div id="menu">
			<div class="col-xs-1 col-sm-2 col-lg-4"><%= image_tag("orange-arrow-left.png", :class => "left_arrow") %></div>
				<div class="col-xs-10 col-sm-8 col-lg-4">
				<p class="menu_item col-xs-3" id="current">Week</p>
				
				<form action="/stats" method="post">
					<select class="week_select col-xs-7" name="time_selected">
					<% for i in 1..53%>
						<option value="<%=  Time.now.at_end_of_week-(7*i).day  %>" <% if @time_selected == (Time.now.at_end_of_week-((7*i).day)).to_s  %><% @time = "stats" 
						@time_selected_2 = Time.now.at_end_of_week-(7*i).day
						@the_time = "stats"
						%>selected<% end %>><%=  (Time.now.at_end_of_week-(7*(i-1).day)).strftime("%b %d")  %> - <%=  (Time.now.at_end_of_week-(7*i).day).strftime("%b %d, '%y")  %></option>
					<% end %>
					</select>
					<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
					<%= hidden_field_tag :time, "stats" %>
					<input class = "col-xs-2 week_submit" type="submit" value="Find">
				</form>
			</div>
			<div class="col-xs-1 col-sm-2 col-lg-4"><%= image_tag("orange-arrow-right.png", :class => "right_arrow") %></div>
			</div>
		</div>
		
		
		
		
		
		
		
		
		
		
	<!--  ***********************************************      Month Select     ***********************************************   -->
		

		
		<div class="row month_select select_2">
			<div id="menu">
			<div class="col-xs-1 col-sm-2 col-lg-4"><%= image_tag("orange-arrow-left.png", :class => "left_arrow") %><</div>
				<div class="col-xs-10 col-sm-8 col-lg-4">
				<p class="menu_item col-xs-3" id="current">Month</p>
				
				<form action="/stats" method="post">
					<select class="week_select col-xs-7" name="time_selected">
					<% for i in 0..11%>
						<option value="<%= (Time.now.at_beginning_of_month-(i*1.month))  %>" <% if @month_selected == (Time.now.at_beginning_of_month-(i*1.month)).to_s  %><% @time = "month" 
					@month_selected_1 = 1
					@time_selected_2 = (Time.now.at_beginning_of_month-(i*1.month))
					@the_time = "month"
					%>selected<% end %>><%=  (Time.now.at_beginning_of_month-(i*1.month)).strftime("%B")  %></option>
					<% end %>
					</select>
					<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
					<%= hidden_field_tag :time, "month" %>
					<input class = "col-xs-2 week_submit" type="submit" value="Find">
				</form>
			</div>
			<div class="col-xs-1 col-sm-2 col-lg-4"><%= image_tag("orange-arrow-right.png", :class => "right_arrow") %></div>
			</div>
		</div>
		
		
		<% if @month_selected_1 == 1  %>
			<script>
				$(document).ready(function(){
					$('.select_1').hide();
					$('.select_2').hide();
					$('.select_3').hide();
					$('.select_2').show();
					select = 2;
				});
			</script>
		<% end %>
		
		
		
		
		
		
		
		
	<!--  ***********************************************      Year Select     ***********************************************   -->
		
		
		
		<div class="row year_select select_3">
			<div id="menu">
			<div class="col-xs-1 col-sm-2 col-lg-4"><%= image_tag("orange-arrow-left.png", :class => "left_arrow") %></div>
				<div class="col-xs-10 col-sm-8 col-lg-4">
				<p class="menu_item col-xs-3" id="current">Year</p>
				
				<form action="/stats" method="post">
					<select class="week_select col-xs-7" name="time_selected">
					<% for i in 0..4%>
						<option value="<%=  (((Time.now.at_beginning_of_year)-(i*1.year))+10.day)  %>" 
						<% if @year_selected == (((Time.now.at_beginning_of_year)-(i*1.year))+10.day).to_s  
							@year_selected_1 = 1
							@the_time = "year"
							@time_selected_2 = ((Time.now.at_beginning_of_year)-(i*1.year))
						%>
							selected
						<% end %>>
						
							<%=  ((Time.now.at_beginning_of_year+10.day)-(i*1.year)).strftime("%Y")  %>
							
						</option>
					<% end %>
					</select>
					<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
					<%= hidden_field_tag :time, "year" %>
					<input class = "col-xs-2 week_submit" type="submit" value="Find">
				</form>
			</div>
			<div class="col-xs-1 col-sm-2 col-lg-4"><%= image_tag("orange-arrow-right.png", :class => "right_arrow") %></div>
			</div>
		</div>
		
		<% if @year_selected_1 == 1  %>
			<script>
			$(document).ready(function(){
				$('.select_1').hide();
				$('.select_2').hide();
				$('.select_3').hide();
				$('.select_3').show();
				select = 3;
				});
			</script>
		<% end %>
	
	
	
	
<!--  ***********************************************      Displaying the current clients     ***********************************************   -->
	
	<div class="row">
			<div class="col-xs-1 col-sm-2 col-lg-4"></div>
			<div class="col-xs-10 col-sm-8 col-lg-4">
				<div id="clients_wrapper">
						<p class="clients"><%= link_to "All", stats_path( client: "all", time: @the_time, time_selected: @time_selected_2), method: :post, class: "clients" %></p>
					<% @clients.each do |time_card| %>
						<p class="clients"><%= link_to time_card.client.titleize, stats_path( client: time_card.client, time: @the_time, time_selected: @time_selected_2), method: :post, class: "clients" %></p>
					<% end %>
				</div>
			</div>
			<div class="col-xs-1 col-sm-2 col-lg-4"></div>
		</div>

	
	
	
	
<!--  ***********************************************      Total Hours     ***********************************************   -->
			
	<div class="row">	
		<div class="col-xs-1 col-sm-2 col-lg-4"></div>
		<p class="col-xs-10 col-sm-8 col-lg-4" id="total">Total: <%=  number_with_precision(@total_hours, :precision => 2) %> hrs</p>
		<div class="col-xs-1 col-sm-2 col-lg-4"></div>
	</div>

    
	
	
	
	
<!--  ***********************************************      Displaying Timecards     ***********************************************   -->


	<% @time_cards.each do |time_card| %>
	
	
		<% if (time_card.date != @date) %>
		<div class="container">
			<% 
				@date = time_card.date
				@current_class = cycle("time_card" , "time_card_2" )
				@client = "New"
			%>
			<div class="<%= @current_class %>">
					
						<div class="row">
							<div class="col-xs-1"></div>
							<p class="col-xs-10" id = "date"><%= time_card.date.strftime("%A, %h %e %G") %></p>
							<div class="col-xs-1"></div>
						</div>

		<% else %>
			<div class="container">
				<div class="<%= @current_class %>">
		<% end %>	
					
					
					
			<% 
				local_start	= Time.new
				local_stop	= Time.new
				local_start = time_card.time_started
				local_stop  = time_card.time_stopped
						
						
				local_start_1 = local_start
				local_stop_1 = local_stop
				local_start = local_start.strftime('%l:%M%P')
				local_stop = local_stop.strftime('%l:%M%P')
			%>
				
			<% if (time_card.client.downcase != @client) %>
				<div class="row">
					<div class="col-xs-2"></div>
					<p class="col-xs-8" id="client"><%= time_card.client.titleize %></p>
				</div>
				<% @client = time_card.client.downcase %>
			<% end %>
				
				<div class="row">
					<div class="col-xs-2"></div>
					<p class="col-xs-8" id="the_time" data-start-time="<%=  %>" data-stop-time="<%=  %>"><%= local_start %> - <%= local_stop %></p>
					<%= link_to image_tag("edit.png", :class => "edit_icon"), edit_time_card_path(time_card) %>
				</div>
				
				<div class="row">
					<div class="col-xs-2"></div>
					<p class="col-xs-8" id="hours"><%= number_with_precision(((local_stop_1 - local_start_1)/3600), :precision => 2) %> hrs</p>
					
				</div>
				
				<div class="row">
					<div class="col-xs-2"></div>
					<p class="col-xs-7" id="message"><%= time_card.message %></p>
					<div class="col-xs-1"></div>
					<%= link_to image_tag("delete.png", :class => "cancel_icon"), time_card, method: :delete, data: { confirm: "Are you sure you want to delete this time card?" } %>
				</div>
				
		</div>
	</div>
	<% end %>